name: Scheduled PowerVC Nosetests

on:
  schedule:
    - cron: '30 4,11 * * *' 
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Execute nosetests with HTML Plugin
        run: |
          # 1. MUST INSTALL ONCE ON RHEL: pip install nose-html-reporting
          
          export TEMPEST_CONFIG_DIR="/var/lib/jenkins/workspace/RTC_code_copy/"
          export TEMPEST_CONFIG="powervc-tempest/etc/powervc_jay.conf"
          export MAPPERS_CONFIG_DIR="/var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/etc/"
          export MAPPERS_CONFIG="mappers.xml"
          
          cd /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest
          
          # This generates a single, portable HTML file
          /usr/local/bin/nosetests --with-xunit --with-allure --logdir=allure-results -s -d -v powervc_tempest/tests/Regression/FVT/compute/test_trusted_profile.py --debug=show -a type=negative
          
          /usr/bin/python3.9 tools/reportgenerator_beta.py -i \
             /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/nosetests.xml -o /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/nosetests.html


        continue-on-error: true

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: PowerVC-Results
          path:
             /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/nosetests.html

      - name: Summary
        if: always()
        run: |
          echo "## PowerVC Report Ready 🚀" >> $GITHUB_STEP_SUMMARY
          echo "Download 'PowerVC-Test-Results' from the Summary page to view the HTML report." >> $GITHUB_STEP_SUMMARY

     
      - name: Send Email via RHEL Local Mail
        if: always()
        run: |
          # Install mailx if missing: sudo dnf install -y smailx
          echo "The PowerVC automated test run has completed. Status: ${{ job.status }}. View details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" | \
          mailx -s "PowerVC Test Report - Run #${{ github.run_number }}" \
          -a /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/nosetests.html \
          jaybvr.in@gmail.com
            Please find the attached HTML report.
          # Attach the single-file report we generated earlier
          attachments: /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/nosetests.html
