name: Scheduled PowerVC Nosetests

on:
  schedule:
    - cron: '30 4,11 * * *' 
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Execute nosetests with HTML Plugin
        run: |
          # 1. MUST INSTALL ONCE ON RHEL: pip install nose-html-reporting
          
          export TEMPEST_CONFIG_DIR="/var/lib/jenkins/workspace/RTC_code_copy/"
          export TEMPEST_CONFIG="powervc-tempest/etc/powervc_jay.conf"
          export MAPPERS_CONFIG_DIR="/var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/etc/"
          export MAPPERS_CONFIG="mappers.xml"
          
          cd /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest
          
          # This generates a single, portable HTML file
          /usr/local/bin/nosetests --with-xunit --with-allure --logdir=allure-results -s -d -v powervc_tempest/tests/Regression/FVT/compute/test_trusted_profile.py --debug=show -a type=negative
          
          /usr/bin/python3.9 tools/reportgenerator_beta.py -i \
             /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/nosetests.xml -o /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/nosetests.html
          cp /var/lib/jenkins/workspace/RTC_code_copy/powervc-tempest/nosetests.xml allure-results
        continue-on-error: true

      - name: Get Allure History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
